baseURL = 'https://blt.github.org/'
languageCode = 'en-us'
title = 'Boston License Tracker (blt)'

theme = "hugo-empty-bootstrap"

# optional, but usually necessary
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
  name = 'Menu 1'
  url = '/menu1/'
  weight = 10
[[menu.main]]
  name = 'Menu 2'
  url = '/menu2/'
  weight = 20

[Params]
  twitter = ""

#  module mounts needed for bootstrap theme to copy font files and bootstrap.bundle.min.js, which includes popper
[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "themes/hugo-empty-bootstrap/node_modules/bootstrap-icons/font/fonts"
target = "static/css/fonts"

[[module.mounts]]
source = "themes/hugo-empty-bootstrap/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "static/js/bootstrap.bundle.min.js"
